### ISSUE TITLE
SwiftPackageManager generate-xcodeproj error in vapor3 project

### ISSUE THREAD

**Issue by NicolasKim** [IBM-Swift/Swift-SMTP#100]
```
error: multiple products named 'Logging' in: Console, swift-log
error: multiple targets named 'Logging' in: Console, swift-log
```

**Comment by helenmasters** [comment]
Hi @NicolasKim,

This was unfortunately a result of us adding support for Apple's swift-log to LoggerAPI which you can read about in our blog here https://developer.ibm.com/swift/2019/06/12/using-swift-log-with-kitura/

I suggest that you take a look at the thread about the logging module name clash on the Swift forums -> https://forums.swift.org/t/logging-module-name-clash-in-vapor-3/25466 for more details as I'm not sure which approach Vapor have taken to fix the problem, it should also help you work around the problem.

Thanks
Helen

**Comment by ianpartridge** [comment]
Yes there's nothing we can do about this from the Kitura side, unfortunately.
