### ISSUE TITLE
Use new BlueSocket connect with timeout API

### ISSUE THREAD

**Issue by quanvo87** [IBM-Swift/Swift-SMTP#39]

**Comment by leanne63** [comment]
Does this, by chance, relate to this message:

> Could not connect to server (<smtp-server>) within specified timeout (<n> seconds). Ensure your server can connect through port 587 or specify which port to connect on. Some SMTP servers may require a longer timeout.

I'm specifying Ports.ssl.rawValue, have changed the timeout all the way to 30 seconds, but still keep getting that message. I can connect and send successfully using other packages.

**Comment by quanvo87** [comment]
It may be, and we will be working on a fix. In the meantime, could you tell what server you're trying to connect to and on what port?

**Comment by leanne63** [comment]
smtpout.secureserver.net, 465

**Comment by quanvo87** [comment]
Can you try port 3535?

**Comment by leanne63** [comment]
Will do....

**Comment by leanne63** [comment]
3535 worked

**Comment by quanvo87** [comment]
Fixed in https://github.com/IBM-Swift/Swift-SMTP/releases/tag/v1.1.1
