### ISSUE TITLE
Could it be used with ios?

### ISSUE THREAD

**Issue by syagaevfeodor** [IBM-Swift/Swift-SMTP#50]
Could it be used with ios?

**Comment by quanvo87** [comment]
I was able to run and pass the tests on a simulator. I would give it a try. Keep in mind, Swift 3.1.1 is required, so make sure your iOS supports that version.

**Comment by syagaevfeodor** [comment]
Can you please help me, how to install your library? When i just add it to
Package.swift, and in console make swift build, xcode give me a error, when
i try to import your library

2017-09-07 23:13 GMT+03:00 Quan Vo <notifications@github.com>:

**Comment by quanvo87** [comment]
Can you post your Package.swift, and what was the error you received?

**Comment by syagaevfeodor** [comment]
The error is: "No such module 'Swift-SMTP' ", and here is my Package.swift,
i'm new to ios dev, so perhaps i did something wrong



[image: Встроенное изображение 1]

2017-09-14 21:45 GMT+03:00 Quan Vo <notifications@github.com>:

**Comment by quanvo87** [comment]
I'm not seeing your Package.swift, but here's an example of what one might look like: 

```
import PackageDescription
let package = Package(
	name: "YourProject",
	targets: [],
	dependencies: [
		.Package(url: "https://github.com/IBM-Swift/Swift-SMTP.git", majorVersion: 1, minor: 1),
	]
)
```

**Comment by syagaevfeodor** [comment]
Yes, i did it sow, but when i write import SwiftSMTP i get a error: "No
such module"

2017-09-14 22:27 GMT+03:00 Quan Vo <notifications@github.com>:

**Comment by quanvo87** [comment]
Once you've assured your Package.swift is correct, run `swift package generate-xcodeproj` in terminal within your project directory, then open the generated xcodeproj. After doing these, do you still get the same error?

**Comment by syagaevfeodor** [comment]
I have this problem while running this ommand in terminal: error: the
package has an unsupported layout, unexpected source file(s) found:

2017-09-14 22:39 GMT+03:00 Quan Vo <notifications@github.com>:

**Comment by quanvo87** [comment]
What version of Swift are you using?

**Comment by syagaevfeodor** [comment]
3.1

**Comment by quanvo87** [comment]
Swift-SMTP currently only supports Swift 3.1.1 (there is a bug in 3.1). Besides that, I am not sure what is causing your problem and will look into it.

**Comment by syagaevfeodor** [comment]
How can i use swift 3.1.1 if with xcode apple provides swift 3.1?

**Comment by quanvo87** [comment]
Xcode 8.3 uses Swift 3.1.1, even though it says 3.1. So if you're using Xcode 8.3, that must not be your problem.

**Comment by quanvo87** [comment]
Is it possible to share your repo so we can take a deep look at the issue?
