### ISSUE TITLE
Tag/Release numbering problem?

### ISSUE THREAD

**Issue by leanne63** [IBM-Swift/Swift-SMTP#51]
I've been trying to fetch v1.1.2 for a project; however, it keeps fetching 1.1.0 instead. Looking at the release and tag listing, I found this strange numbering sequence:

<img width="539" alt="screen shot 2017-09-12 at 5 33 54 pm" src="https://user-images.githubusercontent.com/7043045/30351456-0b713618-97e1-11e7-8c20-1bfd116db49e.png">

Thoughts?

**Comment by quanvo87** [comment]
Fixed by @youming-lin , thanks 😃
