### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by collinhundley** [IBM-Swift/Swift-SMTP#52]
Any chance we can update Package.swift for Swift 4? Most of the other Kitura packages have already been updated.

**Comment by quanvo87** [comment]
@collinhundley I'll try to get this done within a day.

**Comment by quanvo87** [comment]
@collinhundley The latest tag adds Swift 4 support https://github.com/IBM-Swift/Swift-SMTP/releases/tag/v1.1.3
