### ISSUE TITLE
Conflicting requirements with Kitura 2.3

### ISSUE THREAD

**Issue by Davidde94** [IBM-Swift/Swift-SMTP#74]
Package attached:

<img width="786" alt="screen shot 2018-05-01 at 12 33 18" src="https://user-images.githubusercontent.com/14052839/39471626-fbe63b88-4d3b-11e8-9ef4-5953fcce8fea.png">

**Comment by ianpartridge** [comment]
@quanvo87 I think the issue is that all the Blue* repos have gone to 1.0.0 with Swift 4.1 - so SMTP needs to pull in Socket 1.0.0 and SSLService 1.0.0 too.

**Comment by quanvo87** [comment]
https://github.com/IBM-Swift/Swift-SMTP/releases/tag/4.0.1
