### ISSUE TITLE
The dependency graph could not be satisfied

### ISSUE THREAD

**Issue by Zig1375** [IBM-Swift/Swift-SMTP#77]
I try to install only this package and get an error: "The dependency graph could not be satisfied"

**Comment by quanvo87** [comment]
Could you post your Package.swift?

**Comment by Zig1375** [comment]
**Ubuntu 16.04**

`
import PackageDescription

let package = Package(
    name: "RepAPI",
    targets:      [],
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Swift-SMTP.git", majorVersion: 2, minor: 0)
    ]
);
`

Fetching https://github.com/IBM-Swift/Swift-SMTP.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies: 
    https://github.com/IBM-Swift/Swift-SMTP.git @ 2.0.0..<2.1.0
/api/swift/build.sh: line 6: .build/debug/API: No such file or directory

**Comment by quanvo87** [comment]
Can you try using the latest version `4.1`?

**Comment by Zig1375** [comment]
```
root@b9eb29ea529e:/api/swift# swift --version
Swift version 4.1 (swift-4.1-RELEASE)
Target: x86_64-unknown-linux-gnu
root@b9eb29ea529e:/api/swift# swift package update
Updating https://github.com/IBM-Swift/Swift-SMTP.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies: 
    https://github.com/IBM-Swift/Swift-SMTP.git @ 2.0.0..<2.1.0
```

**Comment by quanvo87** [comment]
Sorry, I meant the latest version of `Swift-SMTP`, which is also at `4.1`!

**Comment by Zig1375** [comment]
```
Updating https://github.com/IBM-Swift/Swift-SMTP.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies: 
    https://github.com/IBM-Swift/Swift-SMTP.git @ 3.0.0..<3.1.0
```

**Comment by quanvo87** [comment]
I am not sure why it is trying to pull in Swift-SMTP at 3.0.0 if you're specifying 4.1. Maybe you need to delete your .build folder? Also, are you using the latest Package.swift format? I used this minimal Package.swift and was successfully able to build a new project:

```swift
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "t",
    products: [
        .library(
            name: "t",
            targets: ["t"]),
    ],
    dependencies: [
         .package(url: "https://github.com/IBM-Swift/Swift-SMTP.git", from: "4.0.0"),
    ],
    targets: [
        .target(
            name: "t",
            dependencies: []),
        .testTarget(
            name: "tTests",
            dependencies: ["t"]),
    ]
)
```

**Comment by Zig1375** [comment]
Thank you.
