### ISSUE TITLE
Omission of STARTTLS

### ISSUE THREAD

**Issue by trametheka** [IBM-Swift/Swift-SMTP#79]
This relates to PR https://github.com/IBM-Swift/Swift-SMTP/pull/78 which I have closed for now in favour of an issue for discussion.

I had a bit of a misunderstanding in the migration guide of what this library is expecting to be the behaviour of SMTP/S and STARTTLS which is incorrect.

SMTP over 465 is deprecated/legacy, some references:
- https://en.wikipedia.org/wiki/SMTPS
- https://www.mailgun.com/blog/25-465-587-what-port-should-i-use

[And 465 has been reissued by IANA as well](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt), with many modern mail servers no longer listening on 465 by default.

I can't see a problem with supporting a direct TLS connection at all, I'm not asking this be removed, but STARTTLS is the modern standard and this library should really be supporting it in my opinion.

It was mentioned in the PR that this functionality was removed as the force TLS upgrade was causing issues for some users, but this is exactly how STARTTLS should work if the server requests the TLS upgrade, so maybe I've misunderstood that comment too and there was something else going on? 

[By the STARTTLS spec](https://tools.ietf.org/html/rfc3207), after the commands are issued the existing socket negotiates TLS, effectively upgrading the existing socket to TLS. By the comment https://github.com/IBM-Swift/Swift-SMTP/issues/62#issuecomment-379325650 and what I saw in 
version 2 of this library, the socket was instead being closed and reopened on 465, which is effectively just ignoring the STARTTLS negotiation in favour of a direct connection on port 465, this may have been why users were seeing issues where they had servers not listening on 465.

**Comment by quanvo87** [comment]
Yep you are correct, that's has STARTTLS should work, and I don't see a problem with reintroducing that flow back into the library, with some improvements over the version 2 implementation.

We settled upon the current implementation because while it doesn't exactly follow the SMTP flow, it should give a user all the customization she needs to correctly configure the class and connect to her server. And yes, in version 2, the connection was closed when STARTTLS support was detected, and a new TLS connection was opened. This was because I didn't know how to upgrade an existing connection in [BlueSocket](https://github.com/IBM-Swift/BlueSocket). And I was fine with going away from that implementation cause it seemed silly.

Moving forward with the library, I wanted to follow [Nodemailer](https://nodemailer.com/smtp/) architecture, adding features like `ignoreTLS` and `requireTLS` (it seems like forced upgrade on detect STARTTLS is not always desired for some users).

Lastly, I had read those articles and others and found it difficult to determine what default ports to connect on, TLS or not. You'll notice Nodemailer uses:

> port – is the port to connect to (defaults to 587 is secure is false or 465 if true)

In addition, in my own testing, the current default configuration is the only thing that worked for me for gmail. And I would have to change the configs quite a bit for every other server I tested on. What is the correct default port?

So, again I can see some viable changes to the library, with the above taken into consideration. Thoughts?

**Comment by trametheka** [comment]
> We settled upon the current implementation because while it doesn't exactly follow the SMTP flow, it should give the user all the customization she needs to correctly configure the class and connect to her server.

By this reasoning everything that can be supported should be

> In addition, if you knew your server required TLS, why not just open a TLS connection from the start?

This is fair enough, but in the same way not all servers will support STARTTLS, not all servers will support TLS directly by default, or at all

> In addition, in my own testing, the current default configuration is the only thing that worked for me for gmail. And I would have to change the configs quite a bit for every other server I tested on. What is the correct default port?

This is because you were closing the socket when the starttls command was issued instead of upgrading it to TLS. I can confirm that my PR is working with postfix, gmail and outlook smtp on port 587.

> Lastly, I had read those articles and others and found it difficult to determine what default ports to connect on, TLS or not. You'll notice Nodemailer uses:

Per my link to the IANA port listing, the default ports are 25 for SMTP and 587 for Message Submission. 465, by the standards, has no affiliation with SMTP, it's simply something that has been unofficially adopted. An extension to this is the world has pretty much stopped using port 25 to try and slow down spam. With this in mind, the only default port is 587.

With all this taken into account, I propose the following enum to replace the useTLS bool as well as your proposed bools

```
    /// TLSMode enum for what form of connection security to enforce
    public enum TLSMode {
        /// Follow the requirements of the server with no enforced security. Initiated with no TLS
        case normal
        /// Do not use TLS. Ignore any commands to upgrade to TLS
        case noTLS
        /// Require TLS from the initial connection
        case requireTLS
        /// Enforce the connection upgrades to TLS
        case requireSTARTTLS
    }
```

I hope these are self explanatory.

The one caveat here is noTLS. If the server issues a starttls command, I can confirm with gmail, outlook and postfix that if you ignore it, the server will drop the connection if you try to auth. Currently the SMTPSocket class will try and pull the Auth method from the server commands, which doesn't exist and the connection attempt will fail library/client side anyway.

While gmail supports 465, I cannot find any official documentation for outlook or office 365 that 465 is supported, though it *seems* to work and 465 SMTP is off by default with postfix. With this in mind, I propose also that the SMTP init is updated to the following:
```
    public init(hostname: String,
                email: String,
                password: String,
                port: Int32 = 587,
                tlsMode: TLSMode = .requireSTARTTLS,
                tlsConfiguration: TLSConfiguration? = nil,
                authMethods: [AuthMethod] = [],
                domainName: String = "localhost",
                timeout: UInt = 10) {
```

Let me know your thoughts

**Comment by quanvo87** [comment]
This sounds excellent. Yes, with `noTLS`, the user should expect the possibility of that error.

For `TLSMode`, what is the difference between `normal` and `requireSTARTTLS`?

It sounds like it could be:

```swift
public enum TLSMode {
    /// Start the connection plaintext. Upgrade to TLS if server supports STARTTLS.
    case normal

    /// Connect and send mail over plaintext. Could return an error if server requires TLS.
    case ignoreTLS

    /// Only send mail after successful TLS connection. Returns an error if server does not support STARTTLS.
    case requireTLS
}
```

**Comment by trametheka** [comment]
normal would continue on regardless of a starttls, i.e. as the client you're essentially saying you accept that you will use a non-TLS connection if the server does not request the upgrade.

requireSTARTTLS means that you want the connection to be upgraded to TLS. I.e. as the client if you do not see a starttls command issued, disconnect.

**Comment by quanvo87** [comment]
Ok makes sense. How about this for the enum?:

```swift
public enum TLSMode {
    /// Upgrades the connection to TLS if available, else sends mail over plaintext.
    case normal

    /// Send mail over plaintext and ignore TLS options. Could return an error if server requires TLS.
    case ignoreTLS

    /// Only send mail after successful TLS connection. If a TLS connection cannot be established, return an error.
    case requireTLS
}
```

So this just reduces the cases to 3. I'm not sure both `requireTLS` and `requireSTARTTLS` are needed, and having both convolutes the API a bit in my opinion.

The functionality we lose here is being able to attempt TLS from the start or only after the `HELO/EHLO` command. If someone is going to require TLS, how about we just open a TLS connection from the start?

**Comment by trametheka** [comment]
> The functionality we lose here is being able to attempt TLS from the start or only after the HELO/EHLO command. If someone is going to require TLS, how about we just open a TLS connection from the start?

From https://github.com/IBM-Swift/Swift-SMTP/issues/79#issuecomment-399318288

> > In addition, if you knew your server required TLS, why not just open a TLS connection from the start?
> 
> This is fair enough, but in the same way not all servers will support STARTTLS, not all servers will support TLS directly by default, or at all

I feel we're going in circles here so this will be my last comment on this issue. I will open a pull request shortly and leave it to you to accept/deny. I'd like to see a complete swift implementation like this have a central space instead of companies and others having to rely on a forked version.

For reference, EFF very recently released this as well https://starttls-everywhere.org/faq/
