### ISSUE TITLE
send email from gmail not working

### ISSUE THREAD

**Issue by imgruntw** [IBM-Swift/Swift-SMTP#90]
I can't send email from my gmail account with following code:
`
import SwiftSMTP

public final class SwiftToolBoxCore {
    public func send() -> Void {
        let smtp = SMTP(
            hostname: "smtp.gmail.com",
            email: "myaccount@gmail.com",
            password: "mypassword",
            tlsMode: .requireSTARTTLS
        )

        let fromUser = Mail.User(
            name: "- -",
            email: "myaccount@gmail.com"
        )
        let toUser = Mail.User(
            email: "otheraccount@gmail.com"
        )

        let mail = Mail(
            from: fromUser,
            to: [toUser],
            subject: "subject",
            text: "content text"
        )

        smtp.send(mail) { (error) in
            if let error = error {
                print(error)
            }
        }
    }
}
`

There is no error message. Not secure apps are allowed on my gmail account.  What I am doing wrong?

**Comment by imgruntw** [comment]
I am thanking for speedy responses!
Here is my repo: https://github.com/imgruntw/SwiftToolBox

**Comment by quanvo87** [comment]
How are you running this project? When I run, nothing is happening. It may not be related to Swift-SMTP.

**Comment by imgruntw** [comment]
- run in console: `swift package generate-xcodeproj`
- insert your email account data in Method: `send()` in `/SwiftToolBox/Sources/SwiftToolBoxCore/SwiftToolBoxCore`
- after open SwiftToolBox-project in Xcode and choose `SwiftToolbox` and then run

the Method: `send()` in `/SwiftToolBox/Sources/SwiftToolBoxCore/SwiftToolBoxCore` is executed, but without sending an email and without any errors

**Comment by quanvo87** [comment]
Perhaps execution of the program is ending before the asynchronous task can finish. When I put a print statement in the closure of `smtp.send()`, the print statement is not executed but the program returns with exit code 0.

**Comment by imgruntw** [comment]
Thanks, waiting for end of the asynchronous task with was the solution .
